FROM ruby:2.4

RUN apt-get update -qq && apt-get install -y \
  curl \
  git \
  vim

ENV INSTALL_PATH /app

RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g dredd@4.5.0
RUN npm install -g swagger-to-md
RUN npm install sync-request caseless

RUN groupadd -g 2000 docker -r && useradd -u 1000 -r --no-log-init -m -d $INSTALL_PATH -g docker docker
USER 1000

WORKDIR $INSTALL_PATH

COPY Gemfile Gemfile.lock ./
RUN bundle config --global github.https true
RUN gem install bundler && bundle install --jobs 20 --retry 5

COPY . .
