FROM ruby:2.5.1-alpine

ENV INSTALL_PATH /app

ENV NODE_PACKAGES nodejs nodejs-npm
ENV NODE_BUILD_PACKAGES git
RUN apk add --update --no-cache $NODE_PACKAGES $NODE_BUILD_PACKAGES \
  && npm install -g dredd@4.5.0 \
  && npm install -g swagger-to-md \
  && npm install sync-request caseless \
  && npm cache clean --force \
  && apk del $NODE_BUILD_PACKAGES

RUN addgroup -g 1000 -S docker \
  && adduser -u 1000 -S -G docker docker

WORKDIR $INSTALL_PATH

COPY --chown=docker:docker Gemfile Gemfile.lock ./
RUN bundle config --global github.https true
ENV RUBY_BUILD_PACKAGES ruby-dev build-base linux-headers
RUN apk add --no-cache $RUBY_BUILD_PACKAGES \
  && gem install bundler && bundle install --jobs 20 --retry 5 \
  && apk del $RUBY_BUILD_PACKAGES \
  && chown -R docker:docker /usr/local/bundle

RUN mkdir coverage && chown docker:docker coverage

USER docker
COPY --chown=docker:docker . .

CMD bundle exec rake
